### ISSUE TITLE
Alpha blend smoke over alpha test has sorting issues - Call of Duty 2

### ISSUE THREAD

**Issue by tadpole3159** [NVIDIAGameWorks/dxvk-remix#28]
When looking at alpha test billboards with particle smoke over the top of it you end up with an effect of the smoke shading the transparent part of the alpha test billboards. It happens even if you mark textures as legacy cut out and particle as seen in this video here: https://youtu.be/82S5hSnW6XU

I spoke to peter from Nvidia on discord and he asked me to make this bug. https://discord.com/channels/1028444667789967381/1028444668918235197/1119000631139651624

[COD2_Issues.zip](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11763311/COD2_Issues.zip)

to recreate this effect I've attached my "rtx.conf" file as well as my call of duty 2 profile config's and additional settings to trigger when in game. copy the folder called "main" into the root folder of "Call of Duty 2" folder. mines here "D:\SteamLibrary\steamapps\common\Call of Duty 2" same place the rtx config goes. when in game press F3 which will run some additional game commands and get you around the cheat protection. just lod distance stuff mostly but also fog and static mesh caching. 

1. after installing my configs open multiplayer 
2. open the cod2 console with "`" key and type "devmap mp_carentan" press enter
3. press F3 to trigger my additional console commands **or** type in "/r_smc_enable 0", "/r_portalFineCull 0", "/r_fog 0", "/r_zfar 10000000" and zoom around the smoke from the building in front of you in spectate mode. 
4. "noclip" to fly around if you like
5. line up the smoke with a billboard texture and observe

any map would work though, even single player. the video was recorded on the pointe du hoc assault. 

1. after installing my configs open single player
2. open the cod2 console with "`" key and type "spdevmap duhoc_assult" press enter
3. 3. press F3 to trigger my additional console commands **or** type in "r_smc_enable 0", "r_portalFineCull 0", "r_fog 0", "r_zfar 10000000"
4. climb the rope up the cliff and observe the buildings in billboard trees to the left and right

### Software information
Call of duty 2, RTX remix

### System information
- GPU: 4070ti
- Driver: 531:79
- Wine version: Win 10
- DXVK version: dxvk-remix-f716e16-120-release

### Apitrace file(s)
- Put a link here

### Log files
- d3d9.log:
- d3d11.log:
- dxgi.log:
[d3d9_01.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11763326/d3d9_01.log)
[d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11763327/d3d9.log)
[CoD2MP_s_d3d9.log](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11763334/CoD2MP_s_d3d9.log)

**Comment by pkristof** [comment]
Thanks for filing the issue. To get the cutouts enable `Opacity Micromaps` and disable `Dev Settings \ Developer Options \ Enable` and make sure to remove all but the necessary overrides from your rtx.conf. You have a lot of overrides in there set which cause unwanted behavior and serve no purpose for your use case (i.e. rtx.enableDeveloperOptions = True or rtx.opacityMicromap.enableResetEveryFrame = True, and others). Never set any developer overrides that you don't know what they do and don't need to make progress.

Note, Opacity Micromaps are a performance optimization feature and shouldn't be required to get the cutouts, but in your case there's an issue with how the foliage is resolved without them. For now, force enable Opacity Micromaps. Note, Opacity Micromaps need some time (generally a few seconds) to get generated.

**Comment by tadpole3159** [comment]
oh thank you kristof that's sorted it, looks loads better. I've reset everything and added back my lights and texture settings.
![image](https://github.com/NVIDIAGameWorks/dxvk-remix/assets/134654759/db1ea7c5-7161-408e-a70f-5c2a82ba3392)
unfortunately a crash will happen within about 2 minutes with "Opacity Micromaps" on but I understand its a work around. thank you again. Would you like me to mark this as closed?

**Comment by pkristof** [comment]
No, let's keep the ticket open until the foliage cutouts are properly resolved without Opacity Micromaps being enabled.

Please provide repro steps + rtx.conf for when you see a crash due to Opacity Micromaps being enabled in the game.

**Comment by tadpole3159** [comment]
Yea ok good idea. I've recorded a video until the crash.

https://www.youtube.com/watch?v=KPA7fAUKyaM

looked pretty cool until the crash then, you can see the trees look loads better, particles still have the clipping effect during the explosion sequence. This is my updated to default rtx.cfg
[CODIssues_01.zip](https://github.com/NVIDIAGameWorks/dxvk-remix/files/11780028/CODIssues_01.zip)
I've included the config files again and changed the autoconfig file to have fog. to "r_fog 1".

to get to this level open single player, on the main menu type "spdevmap duhoc_assault"

**Comment by pkristof** [comment]
I have been unable to reproduce the crash on 536.23 driver. What GPU are you using? Does it repro on the latest public driver (536.23+) for you?

Opacity Micromaps may introduce incorrect cutouts due to unstable hashes. I see you have stabilized the hashes for grass and tree foliage in this game, which is a great find, but hashes for other objects (i.e. windows) where the Opacity Micromaps are applied will need to be stabilized as well. If that's not possible, you could specify such textures to be ignored in `rtx.opacityMicromapIgnoreTextures` list, though that's a less preferred approach since it requires manual tagging. It's better to fix the issue on the game side.

**Comment by tadpole3159** [comment]
I'm using a 4070 with driver 531.79. since updating to [this build](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/5336372620) I'm not been able to make it crash either. however switching back to [this build](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/5270432150) and holding the camera looking at trees through smoke causes a crash. takes around 10 minutes maximum (maybe move the camera a little bit). to get here open multiplayer, open console, type in "devmap mp_carentan" enter spectate mode and zoom around, its the burning house right in front of you as you enter the level
![image](https://github.com/NVIDIAGameWorks/dxvk-remix/assets/134654759/c59a35d7-dd03-4a6d-b906-d46803c96afd)

As a side note to completely stabilize all mesh hashes (in current view) enter /r_lockpvs 1 into console command, it stops the culling which is why everything keeps updating. the game is using a portal based PVS system explained here https://www.youtube.com/watch?v=IfCRHSIg6zo
you can see in the usd captures every object with a material gets bundled together into a group and as the camera moves models cull and this updates model hash...super frustrating. any help here would be appreciated but I understand is unique to COD2 and quake engine.

pro tip spawn as a solider, enter "noclip" into the command, fly up VERY high outside the sky box and look down so you can see the **whole** map
![image](https://github.com/NVIDIAGameWorks/dxvk-remix/assets/134654759/03347f0d-28bf-4f37-8500-4b55dd2a7b23)
then enter /r_lockpvs 1 to lock everything in the scene, just press escape and change team to the other team to run aroound as a solider and have stable hashes for the whole level. I've attached lights and models to meshes in create with this process, it's reproducible meaning you can close the game, go through this process again and my rtx changes remain which is exciting for future remix work.

**Comment by pkristof** [comment]
Thanks for checking. Are there any special steps that need to be done for multiplayer to work/launch properly?

**Comment by tadpole3159** [comment]
oh yea that old chestnut. you need to copy your steam.dll found here D:\SteamLibrary to the main folder for cod 2 like this
![image](https://github.com/NVIDIAGameWorks/dxvk-remix/assets/134654759/a2d43ba5-dfde-4afc-ad09-41972a906512)
next plug something into your microphone input on your pc (I know, i just use a pair of headphones :P) and lastly when you launch the screen will be black for about 30 seconds but it will eventually load. you can see the black screen issue here.
https://www.youtube.com/watch?v=hEIvaWR2oMQ

**Comment by pkristof** [comment]
Even with the workaround the multiplayer doesn't launch. Can you confirm if you are still seeing crashes after enabling Opacity Micromaps in multiplayer with the **[build](https://github.com/NVIDIAGameWorks/dxvk-remix/actions/runs/5336372620)** or newer? You said you could hit it with a build that's older than that.

**Comment by pkristof** [comment]
If you still hit a crash, please attach the logs (i.e. CoD2MP_s_d3d9.log) and a gpu dump (i.e. nv-gpudmp) from that run. To get a gpu dump on a GPU crash, make sure your dxvk.conf sets following: `dxvk.enableAftermath = True`

**Comment by pkristof** [comment]
I appreciate you providing the workarounds, but It ran once and never since, it's just not an actionable repro and way too time consuming. If you run into issue with Opacity Micromap in another more easily reproducible scenario, please file another issue.

**Comment by tadpole3159** [comment]
Ok thank you for looking into this , I'll close the bug
